# Generated by Django 5.2.17 on 2026-10-07 15:03

import django.db.models.deletion
import django.db.models.functions.comparison
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cor', models.CharField(choices=[('azul', 'Azul'), ('laranja', 'Laranja'), ('roxo', 'Roxo'), ('vermelho', 'Vermelho'), ('rosa', 'Rosa'), ('ciano', 'Ciano'), ('cinza', 'Cinza'), ('verde', 'Verde'), ('amarelo', 'Amarelo'), ('marrom', 'Marrom'), ('oliva', 'Oliva'), ('indigo', 'Índigo')], max_length=20)),
                ('dono', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': [django.db.models.functions.comparison.Collate(django.db.models.functions.text.Lower('nome'), 'und-x-icu')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('nome'), models.F('dono'), name='gastos_categoria_nome_por_dono', violation_error_message='Já existe uma categoria com este nome.')],
            },
        ),
    ]
