# Generated by Django 5.2.17 on 2026-10-07 22:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0002_categorias_padrao_contas_existentes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MesReferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveSmallIntegerField()),
                ('ano', models.PositiveSmallIntegerField()),
                ('fechado', models.BooleanField(default=False)),
                ('dono', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['ano', 'mes'],
                'constraints': [models.CheckConstraint(condition=models.Q(('mes__gte', 1), ('mes__lte', 12)), name='gastos_mes_mes_valido'), models.CheckConstraint(condition=models.Q(('ano__gte', 2000), ('ano__lte', 2100)), name='gastos_mes_ano_valido'), models.UniqueConstraint(fields=('dono', 'ano', 'mes'), name='gastos_mes_unico_por_dono', violation_error_message='Este mês já foi criado.')],
            },
        ),
    ]
